# Generated by Django 3.1.2 on 2020-10-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_collegename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
