# Generated by Django 3.1.2 on 2020-10-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_fulluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.PositiveIntegerField()),
                ('event_name', models.CharField(max_length=100)),
                ('event_id', models.PositiveIntegerField()),
                ('college_name', models.CharField(max_length=100)),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
