# Generated by Django 3.1.2 on 2020-10-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20201025_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.fulluser'),
        ),
    ]
